export const AppConstants = {
  RAZORPAY_KEY_ID: "your_key_id",
  SHOP_NAME: "SYNDICATE PRINTERS",
  SHOP_ADDRESS_LINE1: "BHARATHY SALAI, OPP JAMBAZAR POLICE STATION,",
  SHOP_ADDRESS_LINE2: "ROYAPETTAH, CHENNAI - 14",
  SHOP_CONTACT: "PH: +91 9840031990",
  SHOP_GSTIN: "33ALSPS7215E1ZW",
};
